[package]
name = "hyper-tokio-io"
version = "0.1.0"
edition = "2024"
description = "Utilities type `TokioIo` from hyper-util"
license = "MIT"

[dependencies]
hyper = "1.6.0"
tokio = { version = "1", default-features = false }

pin-project-lite = "0.2.4"
